title: Jekyll-PlantUML
remote_theme: pages-themes/cayman@v0.2.0

repository: RichDom2185/jekyll-plantuml
markdown: kramdown

description: Adds PlantUML language support to code blocks. GitHub Pages-compatible.

plugins:
  - jemoji
  - jekyll-remote-theme
